### ISSUE TITLE
resources.html background image too large

### ISSUE THREAD

**Issue by mobeets** [WEPCo/WEPCo.github.io#12]
hey man! this page is getting fuller by the day! looks awesome.

just noticing that the resources.html wood background takes a long time to load on my currently-poor internet connection. maybe consider a shorter image that can be tiled to fill the page.

**Comment by emreerdener** [comment]
yeah that's an issue overall actually. I need to resize / optimize the backgrounds images across the board.

**Comment by emreerdener** [comment]
Another issue with the background images is that they "bounce" on mobile. When scrolling down the page on mobile the background image will shift (I assume to cover the page as you continue to scroll), which isn't the greatest experience.
