### ISSUE TITLE
Slider in Mobile - Swipe

### ISSUE THREAD

**Issue by emreerdener** [WEPCo/WEPCo.github.io#3]
I've loaded in the javascript (in main.js), but have not set it up.

It allows for swiping (left/right) on mobile devices, which I want to connect the imageslider to.

**Comment by mobeets** [comment]
Not sure if this is what your issue is (what is the issue?), but one thing to note is that in jquery you just need one `$(function() {});` part per file, and all your javascript code goes inside of that. So something like this:

```
$(function() {

  $(".rslides").responsiveSlides({
  auto: true, //animate automatically
  speed: 500, //speed in milliseconds
  timeout: 3000, //time between slide transitions
    });
  $(".rslides").swipe({
		swipe:function(swipe, right, distance, duration, fingerCount, fingerData) {
      	$(this).text("You swiped " + direction );  
      }
   });
});
   
```

**Comment by emreerdener** [comment]
I've solved this issue by replacing the original slider with one that has touchscreen compatibility built in. hooray!
