### ISSUE TITLE
Background Image

### ISSUE THREAD

**Issue by emreerdener** [WEPCo/WEPCo.github.io#4]
Any attempt to specify a background image via the "html" or "body" tags (in css) are not displayed.
I think there is some line of css somewhere else in my code that is overriding it, but I'm not sure.

So, as of now: no background images appear.

**Comment by emreerdener** [comment]
@mobeets do you have any ideas here?

At one point I had defined a <div> color for the footer, which worked (before I eventually made it a "well" element), but above the footer div something is over-riding any colors or background images.

As an (useful) experiment I have been trying to set the background-color of the <div class="background"> located just below the navbar.
*Note: the parent div class="container-fluid"> just sets the container to full-width versus padding.

**Comment by mobeets** [comment]
I don't understand the issue..."any attempt to specify a background image _via the or_" ?

**Comment by emreerdener** [comment]
Yeah sorry that was confusingly written.

Basically, I cannot define a background color for the body (or any container).
I can't figure out why, but I think something is over-riding any css I make?

**Comment by emreerdener** [comment]
oh when I wrote the first comment I didn't realize these comment fields accept/publish html tags

**Comment by mobeets** [comment]
haha oh i see! that's weird. as for the actual issue, not sure yet but i'll look into it

**Comment by emreerdener** [comment]
Aha! I've solved the problem!
Turns out it was as simple as the image path being set into another folder that also had an "image" folder <--thus causing the confusion.
