### ISSUE TITLE
hovering footer has a mind of its own

### ISSUE THREAD

**Issue by mobeets** [WEPCo/WEPCo.github.io#5]
wow! this page is really coming together. the events section looks great.

on my laptop, when the page fills the screen, if i scroll around the page with my trackpad the footer doesn't seem to move in tandem with the rest of the page. it's like whatever that's pinning it to the bottom has a delayed reaction to the scrolling.

if i make the page smaller, e.g., five inches or so, this problem goes away.

**Comment by emreerdener** [comment]
Weird. I can't seem to replicate this issue on my end. Are you using Chrome?
Can you post screenshots on here?

**Comment by mobeets** [comment]
if i scroll down super fast, the footer lags behind. i caught it in the act with two screenshots:
This is when it's lagging:
![screen shot 2015-03-25 at 5 39 53 pm](https://cloud.githubusercontent.com/assets/1677179/6837053/1564386a-d316-11e4-8e2b-56de2b1b98c5.png)
It should look like:
![screen shot 2015-03-25 at 5 40 02 pm](https://cloud.githubusercontent.com/assets/1677179/6837055/17c3669e-d316-11e4-8eae-6214eb6bf6aa.png)

**Comment by mobeets** [comment]
Yep, it's a Chrome issue! In Firefox it doesn't happen.

**Comment by emreerdener** [comment]
hah! that's weird!
