### ISSUE TITLE
page width slightly too large

### ISSUE THREAD

**Issue by mobeets** [WEPCo/WEPCo.github.io#6]
we talked about this problem earlier, so you know what i'm talking about.

basically, when the screen is full size on a laptop, there's still some horizontal scroll going on. not sure why this is. i've definitely had this problem before with bootstrap, so if i remember how i fixed it i'll let you know.

**Comment by mobeets** [comment]
[this](https://scotch.io/bar-talk/bootstrap-3-tips-and-tricks-you-might-not-know#media-query-break-points) might help

**Comment by emreerdener** [comment]
ah I actually fixed it (for now) with:
html, body { overflow-x: hidden; }

**Comment by mobeets** [comment]
nice
